baseurl: '/documentation-stage'
exclude: [README.md, Gemfile, Gemfile.lock, CNAME]
apiDomain: "https://stage-api.wizehive.com"
authDomain: "https://stage-auth.wizehive.com"
demoClientId: "rest-api-quick-start-demo"
apiKey: false