version: 1
exclude: [README.md, Gemfile, Gemfile.lock, CNAME]
apiDomain: "https://api.zenginehq.com"
clientDomain: "https://platform.zenginehq.com"
authDomain: "https://auth.zenginehq.com"
supportDomain: "https://support.zenginehq.com"
developerDomain: https://github.com/ZengineHQ/developers
demoClientId: "rest-api-quick-start-demo"
rootDomain: zenginehq.com
apiKey: false
kramdown:
  input: GFM # enable github flavored markdown
productName: Zengine
logo: <span class="logo">Zengine</span> Developers</span>
