defaults:
-
    scope:
        path: "" # an empty string here means all files in the project
    values:
        layout: default
        apiDomain: "https://api.wizehive.com"
        authDomain: "https://auth.wizehive.com"
        demoClientId: "rest-api-quick-start-demo"
baseurl: '/sandy-docs'
exclude: [README.md, Gemfile, Gemfile.lock]
github: [Repository metadata]